# Generated by Django 4.2.7 on 2023-12-08 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CompletedCourse',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.course')),
                ('grade_achieved', models.CharField(max_length=2)),
            ],
            bases=('api.course',),
        ),
        migrations.CreateModel(
            name='OngoingCourse',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.course')),
                ('remaining_seats', models.IntegerField()),
            ],
            bases=('api.course',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
                ('courses_completed', models.ManyToManyField(blank=True, related_name='completed_students', to='api.course')),
                ('courses_enrolled', models.ManyToManyField(related_name='enrolled_students', to='api.course')),
            ],
        ),
    ]
